---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-terraform
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:v0.17.0
  runtimeConfigRef:
    name: terraform
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: terraform
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              # TF_VAR here is important
              # It defines a Terraform variable
              # https://developer.hashicorp.com/terraform/cli/config/environment-variables
              #
              # Pull details from dt-details secret and set and env vars
              # on the terraform-provider pod
              # These will be used in the configuration block below
              # to dynamically inject secret data
              env:
                - name: TF_VAR_DYNATRACE_URL
                  valueFrom:
                    secretKeyRef:
                      name: dt-details
                      key: DYNATRACE_ENV_URL
                - name: TF_VAR_DYNATRACE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: dt-details
                      key: DYNATRACE_API_TOKEN
              # for demo purposes
              # run in -d debug mode
              # also poll for changes more quickly (every 30s)
              args:
                - -d
                - --poll=30s
                - --max-reconcile-rate=10
